name: crgtransp72app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter_svg: ^2.0.10+1
  flutter_combo_box: ^0.0.1
  intl: ^0.20.2
  flutter_form_builder: ^10.0.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  device_preview: ^1.1.0
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2 
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_image_compress: ^2.4.0
  file_picker: ^8.1.3
  carousel_slider: ^5.0.0
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  path: any
  shared_preferences: any
  path_provider: any
  flutter_launcher_icons: ^0.14.3
  recaptcha_v3: ^0.2.0
  googleapis_auth: ^2.0.0
  dio: ^5.9.0 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/fotouser.png
   - assets/service_account.json
android:
  app:
    icons:
      adaptive_icon_background: 'assets/images/icon.png'
      adaptive_icon_foreground: 'assets/images/icon.png'

flutter_launcher_icons:
  android: "launcher_icon" # имя иконки для Android
  ios: true # для iOS
  image_path: "assets/images/icon/icon.png" # путь к вашей иконке
  min_sdk_android: 21 # минимальная версия Android SDK
  
  # Дополнительные настройки (опционально):
  adaptive_icon_background: "#ffffff" # цвет фона для адаптивных иконок Android
  adaptive_icon_foreground: "assets/images/icon/icon_foreground.png" # передний план для адаптивных иконок
  remove_alpha_ios: true # удалить прозрачность для iOS
  web:
    generate: true
    image_path: "assets/images/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon/icon.png"      